<%@page import="java.util.List"%>
<%@page import="java.util.TimeZone"%>
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>
<!DOCTYPE html>
<html>
<head>
<link rel="stylesheet" href="Home.css">
<meta charset="ISO-8859-1">
<title>Time Zone Conversion</title>
</head>
<body style="background-color: blanchedalmond">
<h1>Time Conversion by Country</h1>
	<div
		style="background-color: dimgrey; margin: 10%; border: solid; padding: 5%">
		<form action="TimeZoneController">
			Enter Time Zone <input type="text" name="tz"> <input type="submit"
				value="Convert" name="convert"><br>
		</form>
		
		<%!
		String ans = "";
		%>
		<%
		ans = (String)session.getAttribute("ans");
		%><br>
		<h5>--------------------------------------------------------------------------------------------------------- Last Conversion ----------------------------------------------------------------------------------------------------------</h5>
		<h2><%=ans%></h2>
		
	</div>
	
	<div
		style="background-color: dimgrey; margin: 10%; border: solid; padding: 5%">
		<h3>Available Time Zones</h3>
        <br>(GMT0:00) Africa/Abidjan
        <br>(GMT0:00) Africa/Accra
        <br>(GMT+3:00) Africa/Addis_Ababa
        <br>(GMT+1:00) Africa/Algiers
        <br>(GMT+3:00) Africa/Asmara
        <br>(GMT+3:00) Africa/Asmera
        <br>(GMT0:00) Africa/Bamako
        <br>(GMT+1:00) Africa/Bangui
        <br>(GMT0:00) Africa/Banjul
        <br>(GMT0:00) Africa/Bissau
        <br>(GMT+2:00) Africa/Blantyre
        <br>(GMT+1:00) Africa/Brazzaville
        <br>(GMT+2:00) Africa/Bujumbura
        <br>(GMT+2:00) Africa/Cairo
        <br>(GMT0:00) Africa/Casablanca
        <br>(GMT+1:00) Africa/Ceuta
        <br>(GMT0:00) Africa/Conakry
        <br>(GMT0:00) Africa/Dakar
        <br>(GMT+3:00) Africa/Dar_es_Salaam
        <br>(GMT+3:00) Africa/Djibouti
        <br>(GMT+1:00) Africa/Douala
        <br>(GMT0:00) Africa/El_Aaiun
        <br>(GMT0:00) Africa/Freetown
        <br>(GMT+2:00) Africa/Gaborone
        <br>(GMT+2:00) Africa/Harare
        <br>(GMT+2:00) Africa/Johannesburg
        <br>(GMT+2:00) Africa/Juba
        <br>(GMT+3:00) Africa/Kampala
        <br>(GMT+2:00) Africa/Khartoum
        <br>(GMT+2:00) Africa/Kigali
        <br>(GMT+1:00) Africa/Kinshasa
        <br>(GMT+1:00) Africa/Lagos
        <br>(GMT+1:00) Africa/Libreville
        <br>(GMT0:00) Africa/Lome
        <br>(GMT+1:00) Africa/Luanda
        <br>(GMT+2:00) Africa/Lubumbashi
        <br>(GMT+2:00) Africa/Lusaka
        <br>(GMT+1:00) Africa/Malabo
        <br>(GMT+2:00) Africa/Maputo
        <br>(GMT+2:00) Africa/Maseru
        <br>(GMT+2:00) Africa/Mbabane
        <br>(GMT+3:00) Africa/Mogadishu
        <br>(GMT0:00) Africa/Monrovia
        <br>(GMT+3:00) Africa/Nairobi
        <br>(GMT+1:00) Africa/Ndjamena
        <br>(GMT+1:00) Africa/Niamey
        <br>(GMT0:00) Africa/Nouakchott
        <br>(GMT0:00) Africa/Ouagadougou
        <br>(GMT+1:00) Africa/Porto-Novo
        <br>(GMT0:00) Africa/Sao_Tome
        <br>(GMT0:00) Africa/Timbuktu
        <br>(GMT+2:00) Africa/Tripoli
        <br>(GMT+1:00) Africa/Tunis
        <br>(GMT+1:00) Africa/Windhoek
        <br>(GMT-10:00) America/Adak
        <br>(GMT-9:00) America/Anchorage
        <br>(GMT-4:00) America/Anguilla
        <br>(GMT-4:00) America/Antigua
        <br>(GMT-3:00) America/Araguaina
        <br>(GMT-3:00) America/Argentina/Buenos_Aires
        <br>(GMT-3:00) America/Argentina/Catamarca
        <br>(GMT-3:00) America/Argentina/ComodRivadavia
        <br>(GMT-3:00) America/Argentina/Cordoba
        <br>(GMT-3:00) America/Argentina/Jujuy
        <br>(GMT-3:00) America/Argentina/La_Rioja
        <br>(GMT-3:00) America/Argentina/Mendoza
        <br>(GMT-3:00) America/Argentina/Rio_Gallegos
        <br>(GMT-3:00) America/Argentina/Salta
        <br>(GMT-3:00) America/Argentina/San_Juan
        <br>(GMT-3:00) America/Argentina/San_Luis
        <br>(GMT-3:00) America/Argentina/Tucuman
        <br>(GMT-3:00) America/Argentina/Ushuaia
        <br>(GMT-4:00) America/Aruba
        <br>(GMT-4:00) America/Asuncion
        <br>(GMT-5:00) America/Atikokan
        <br>(GMT-10:00) America/Atka
        <br>(GMT-3:00) America/Bahia
        <br>(GMT-6:00) America/Bahia_Banderas
        <br>(GMT-4:00) America/Barbados
        <br>(GMT-3:00) America/Belem
        <br>(GMT-6:00) America/Belize
        <br>(GMT-4:00) America/Blanc-Sablon
        <br>(GMT-4:00) America/Boa_Vista
        <br>(GMT-5:00) America/Bogota
        <br>(GMT-7:00) America/Boise
        <br>(GMT-3:00) America/Buenos_Aires
        <br>(GMT-7:00) America/Cambridge_Bay
        <br>(GMT-4:00) America/Campo_Grande
        <br>(GMT-5:00) America/Cancun
        <br>(GMT-4:00) America/Caracas
        <br>(GMT-3:00) America/Catamarca
        <br>(GMT-3:00) America/Cayenne
        <br>(GMT-5:00) America/Cayman
        <br>(GMT-6:00) America/Chicago
        <br>(GMT-7:00) America/Chihuahua
        <br>(GMT-5:00) America/Coral_Harbour
        <br>(GMT-3:00) America/Cordoba
        <br>(GMT-6:00) America/Costa_Rica
        <br>(GMT-7:00) America/Creston
        <br>(GMT-4:00) America/Cuiaba
        <br>(GMT-4:00) America/Curacao
        <br>(GMT0:00) America/Danmarkshavn
        <br>(GMT-7:00) America/Dawson
        <br>(GMT-7:00) America/Dawson_Creek
        <br>(GMT-7:00) America/Denver
        <br>(GMT-5:00) America/Detroit
        <br>(GMT-4:00) America/Dominica
        <br>(GMT-7:00) America/Edmonton
        <br>(GMT-5:00) America/Eirunepe
        <br>(GMT-6:00) America/El_Salvador
        <br>(GMT-8:00) America/Ensenada
        <br>(GMT-7:00) America/Fort_Nelson
        <br>(GMT-5:00) America/Fort_Wayne
        <br>(GMT-3:00) America/Fortaleza
        <br>(GMT-4:00) America/Glace_Bay
        <br>(GMT-3:00) America/Godthab
        <br>(GMT-4:00) America/Goose_Bay
        <br>(GMT-5:00) America/Grand_Turk
        <br>(GMT-4:00) America/Grenada
        <br>(GMT-4:00) America/Guadeloupe
        <br>(GMT-6:00) America/Guatemala
        <br>(GMT-5:00) America/Guayaquil
        <br>(GMT-4:00) America/Guyana
        <br>(GMT-4:00) America/Halifax
        <br>(GMT-5:00) America/Havana
        <br>(GMT-7:00) America/Hermosillo
        <br>(GMT-5:00) America/Indiana/Indianapolis
        <br>(GMT-6:00) America/Indiana/Knox
        <br>(GMT-5:00) America/Indiana/Marengo
        <br>(GMT-5:00) America/Indiana/Petersburg
        <br>(GMT-6:00) America/Indiana/Tell_City
        <br>(GMT-5:00) America/Indiana/Vevay
        <br>(GMT-5:00) America/Indiana/Vincennes
        <br>(GMT-5:00) America/Indiana/Winamac
        <br>(GMT-5:00) America/Indianapolis
        <br>(GMT-7:00) America/Inuvik
        <br>(GMT-5:00) America/Iqaluit
        <br>(GMT-5:00) America/Jamaica
        <br>(GMT-3:00) America/Jujuy
        <br>(GMT-9:00) America/Juneau
        <br>(GMT-5:00) America/Kentucky/Louisville
        <br>(GMT-5:00) America/Kentucky/Monticello
        <br>(GMT-6:00) America/Knox_IN
        <br>(GMT-4:00) America/Kralendijk
        <br>(GMT-4:00) America/La_Paz
        <br>(GMT-5:00) America/Lima
        <br>(GMT-8:00) America/Los_Angeles
        <br>(GMT-5:00) America/Louisville
        <br>(GMT-4:00) America/Lower_Princes
        <br>(GMT-3:00) America/Maceio
        <br>(GMT-6:00) America/Managua
        <br>(GMT-4:00) America/Manaus
        <br>(GMT-4:00) America/Marigot
        <br>(GMT-4:00) America/Martinique
        <br>(GMT-6:00) America/Matamoros
        <br>(GMT-7:00) America/Mazatlan
        <br>(GMT-3:00) America/Mendoza
        <br>(GMT-6:00) America/Menominee
        <br>(GMT-6:00) America/Merida
        <br>(GMT-9:00) America/Metlakatla
        <br>(GMT-6:00) America/Mexico_City
        <br>(GMT-3:00) America/Miquelon
        <br>(GMT-4:00) America/Moncton
        <br>(GMT-6:00) America/Monterrey
        <br>(GMT-3:00) America/Montevideo
        <br>(GMT-5:00) America/Montreal
        <br>(GMT-4:00) America/Montserrat
        <br>(GMT-5:00) America/Nassau
        <br>(GMT-5:00) America/New_York
        <br>(GMT-5:00) America/Nipigon
        <br>(GMT-9:00) America/Nome
        <br>(GMT-2:00) America/Noronha
        <br>(GMT-6:00) America/North_Dakota/Beulah
        <br>(GMT-6:00) America/North_Dakota/Center
        <br>(GMT-6:00) America/North_Dakota/New_Salem
        <br>(GMT-3:00) America/Nuuk
        <br>(GMT-7:00) America/Ojinaga
        <br>(GMT-5:00) America/Panama
        <br>(GMT-5:00) America/Pangnirtung
        <br>(GMT-3:00) America/Paramaribo
        <br>(GMT-7:00) America/Phoenix
        <br>(GMT-5:00) America/Port-au-Prince
        <br>(GMT-4:00) America/Port_of_Spain
        <br>(GMT-5:00) America/Porto_Acre
        <br>(GMT-4:00) America/Porto_Velho
        <br>(GMT-4:00) America/Puerto_Rico
        <br>(GMT-3:00) America/Punta_Arenas
        <br>(GMT-6:00) America/Rainy_River
        <br>(GMT-6:00) America/Rankin_Inlet
        <br>(GMT-3:00) America/Recife
        <br>(GMT-6:00) America/Regina
        <br>(GMT-6:00) America/Resolute
        <br>(GMT-5:00) America/Rio_Branco
        <br>(GMT-3:00) America/Rosario
        <br>(GMT-8:00) America/Santa_Isabel
        <br>(GMT-3:00) America/Santarem
        <br>(GMT-4:00) America/Santiago
        <br>(GMT-4:00) America/Santo_Domingo
        <br>(GMT-3:00) America/Sao_Paulo
        <br>(GMT-1:00) America/Scoresbysund
        <br>(GMT-7:00) America/Shiprock
        <br>(GMT-9:00) America/Sitka
        <br>(GMT-4:00) America/St_Barthelemy
        <br>(GMT-3:30) America/St_Johns
        <br>(GMT-4:00) America/St_Kitts
        <br>(GMT-4:00) America/St_Lucia
        <br>(GMT-4:00) America/St_Thomas
        <br>(GMT-4:00) America/St_Vincent
        <br>(GMT-6:00) America/Swift_Current
        <br>(GMT-6:00) America/Tegucigalpa
        <br>(GMT-4:00) America/Thule
        <br>(GMT-5:00) America/Thunder_Bay
        <br>(GMT-8:00) America/Tijuana
        <br>(GMT-5:00) America/Toronto
        <br>(GMT-4:00) America/Tortola
        <br>(GMT-8:00) America/Vancouver
        <br>(GMT-4:00) America/Virgin
        <br>(GMT-7:00) America/Whitehorse
        <br>(GMT-6:00) America/Winnipeg
        <br>(GMT-9:00) America/Yakutat
        <br>(GMT-7:00) America/Yellowknife
        <br>(GMT+11:00) Antarctica/Casey
        <br>(GMT+7:00) Antarctica/Davis
        <br>(GMT+10:00) Antarctica/DumontDUrville
        <br>(GMT+10:00) Antarctica/Macquarie
        <br>(GMT+5:00) Antarctica/Mawson
        <br>(GMT+12:00) Antarctica/McMurdo
        <br>(GMT-3:00) Antarctica/Palmer
        <br>(GMT-3:00) Antarctica/Rothera
        <br>(GMT+12:00) Antarctica/South_Pole
        <br>(GMT+3:00) Antarctica/Syowa
        <br>(GMT0:00) Antarctica/Troll
        <br>(GMT+6:00) Antarctica/Vostok
        <br>(GMT+1:00) Arctic/Longyearbyen
        <br>(GMT+3:00) Asia/Aden
        <br>(GMT+6:00) Asia/Almaty
        <br>(GMT+2:00) Asia/Amman
        <br>(GMT+12:00) Asia/Anadyr
        <br>(GMT+5:00) Asia/Aqtau
        <br>(GMT+5:00) Asia/Aqtobe
        <br>(GMT+5:00) Asia/Ashgabat
        <br>(GMT+5:00) Asia/Ashkhabad
        <br>(GMT+5:00) Asia/Atyrau
        <br>(GMT+3:00) Asia/Baghdad
        <br>(GMT+3:00) Asia/Bahrain
        <br>(GMT+4:00) Asia/Baku
        <br>(GMT+7:00) Asia/Bangkok
        <br>(GMT+7:00) Asia/Barnaul
        <br>(GMT+2:00) Asia/Beirut
        <br>(GMT+6:00) Asia/Bishkek
        <br>(GMT+8:00) Asia/Brunei
        <br>(GMT+5:30) Asia/Calcutta
        <br>(GMT+9:00) Asia/Chita
        <br>(GMT+8:00) Asia/Choibalsan
        <br>(GMT+8:00) Asia/Chongqing
        <br>(GMT+8:00) Asia/Chungking
        <br>(GMT+5:30) Asia/Colombo
        <br>(GMT+6:00) Asia/Dacca
        <br>(GMT+2:00) Asia/Damascus
        <br>(GMT+6:00) Asia/Dhaka
        <br>(GMT+9:00) Asia/Dili
        <br>(GMT+4:00) Asia/Dubai
        <br>(GMT+5:00) Asia/Dushanbe
        <br>(GMT+2:00) Asia/Famagusta
        <br>(GMT+2:00) Asia/Gaza
        <br>(GMT+8:00) Asia/Harbin
        <br>(GMT+2:00) Asia/Hebron
        <br>(GMT+7:00) Asia/Ho_Chi_Minh
        <br>(GMT+8:00) Asia/Hong_Kong
        <br>(GMT+7:00) Asia/Hovd
        <br>(GMT+8:00) Asia/Irkutsk
        <br>(GMT+3:00) Asia/Istanbul
        <br>(GMT+7:00) Asia/Jakarta
        <br>(GMT+9:00) Asia/Jayapura
        <br>(GMT+2:00) Asia/Jerusalem
        <br>(GMT+4:30) Asia/Kabul
        <br>(GMT+12:00) Asia/Kamchatka
        <br>(GMT+5:00) Asia/Karachi
        <br>(GMT+6:00) Asia/Kashgar
        <br>(GMT+5:45) Asia/Kathmandu
        <br>(GMT+5:45) Asia/Katmandu
        <br>(GMT+9:00) Asia/Khandyga
        <br>(GMT+5:30) Asia/Kolkata
        <br>(GMT+7:00) Asia/Krasnoyarsk
        <br>(GMT+8:00) Asia/Kuala_Lumpur
        <br>(GMT+8:00) Asia/Kuching
        <br>(GMT+3:00) Asia/Kuwait
        <br>(GMT+8:00) Asia/Macao
        <br>(GMT+8:00) Asia/Macau
        <br>(GMT+11:00) Asia/Magadan
        <br>(GMT+8:00) Asia/Makassar
        <br>(GMT+8:00) Asia/Manila
        <br>(GMT+4:00) Asia/Muscat
        <br>(GMT+2:00) Asia/Nicosia
        <br>(GMT+7:00) Asia/Novokuznetsk
        <br>(GMT+7:00) Asia/Novosibirsk
        <br>(GMT+6:00) Asia/Omsk
        <br>(GMT+5:00) Asia/Oral
        <br>(GMT+7:00) Asia/Phnom_Penh
        <br>(GMT+7:00) Asia/Pontianak
        <br>(GMT+9:00) Asia/Pyongyang
        <br>(GMT+3:00) Asia/Qatar
        <br>(GMT+6:00) Asia/Qostanay
        <br>(GMT+5:00) Asia/Qyzylorda
        <br>(GMT+6:30) Asia/Rangoon
        <br>(GMT+3:00) Asia/Riyadh
        <br>(GMT+7:00) Asia/Saigon
        <br>(GMT+11:00) Asia/Sakhalin
        <br>(GMT+5:00) Asia/Samarkand
        <br>(GMT+9:00) Asia/Seoul
        <br>(GMT+8:00) Asia/Shanghai
        <br>(GMT+8:00) Asia/Singapore
        <br>(GMT+11:00) Asia/Srednekolymsk
        <br>(GMT+8:00) Asia/Taipei
        <br>(GMT+5:00) Asia/Tashkent
        <br>(GMT+4:00) Asia/Tbilisi
        <br>(GMT+3:30) Asia/Tehran
        <br>(GMT+2:00) Asia/Tel_Aviv
        <br>(GMT+6:00) Asia/Thimbu
        <br>(GMT+6:00) Asia/Thimphu
        <br>(GMT+9:00) Asia/Tokyo
        <br>(GMT+7:00) Asia/Tomsk
        <br>(GMT+8:00) Asia/Ujung_Pandang
        <br>(GMT+8:00) Asia/Ulaanbaatar
        <br>(GMT+8:00) Asia/Ulan_Bator
        <br>(GMT+6:00) Asia/Urumqi
        <br>(GMT+10:00) Asia/Ust-Nera
        <br>(GMT+7:00) Asia/Vientiane
        <br>(GMT+10:00) Asia/Vladivostok
        <br>(GMT+9:00) Asia/Yakutsk
        <br>(GMT+6:30) Asia/Yangon
        <br>(GMT+5:00) Asia/Yekaterinburg
        <br>(GMT+4:00) Asia/Yerevan
        <br>(GMT-1:00) Atlantic/Azores
        <br>(GMT-4:00) Atlantic/Bermuda
        <br>(GMT0:00) Atlantic/Canary
        <br>(GMT-1:00) Atlantic/Cape_Verde
        <br>(GMT0:00) Atlantic/Faeroe
        <br>(GMT0:00) Atlantic/Faroe
        <br>(GMT+1:00) Atlantic/Jan_Mayen
        <br>(GMT0:00) Atlantic/Madeira
        <br>(GMT0:00) Atlantic/Reykjavik
        <br>(GMT-2:00) Atlantic/South_Georgia
        <br>(GMT0:00) Atlantic/St_Helena
        <br>(GMT-3:00) Atlantic/Stanley
        <br>(GMT+10:00) Australia/ACT
        <br>(GMT+9:30) Australia/Adelaide
        <br>(GMT+10:00) Australia/Brisbane
        <br>(GMT+9:30) Australia/Broken_Hill
        <br>(GMT+10:00) Australia/Canberra
        <br>(GMT+10:00) Australia/Currie
        <br>(GMT+9:30) Australia/Darwin
        <br>(GMT+8:45) Australia/Eucla
        <br>(GMT+10:00) Australia/Hobart
        <br>(GMT+10:30) Australia/LHI
        <br>(GMT+10:00) Australia/Lindeman
        <br>(GMT+10:30) Australia/Lord_Howe
        <br>(GMT+10:00) Australia/Melbourne
        <br>(GMT+10:00) Australia/NSW
        <br>(GMT+9:30) Australia/North
        <br>(GMT+8:00) Australia/Perth
        <br>(GMT+10:00) Australia/Queensland
        <br>(GMT+9:30) Australia/South
        <br>(GMT+10:00) Australia/Sydney
        <br>(GMT+10:00) Australia/Tasmania
        <br>(GMT+10:00) Australia/Victoria
        <br>(GMT+8:00) Australia/West
        <br>(GMT+9:30) Australia/Yancowinna
        <br>(GMT-5:00) Brazil/Acre
        <br>(GMT-2:00) Brazil/DeNoronha
        <br>(GMT-3:00) Brazil/East
        <br>(GMT-4:00) Brazil/West
        <br>(GMT+1:00) CET
        <br>(GMT-6:00) CST6CDT
        <br>(GMT-4:00) Canada/Atlantic
        <br>(GMT-6:00) Canada/Central
        <br>(GMT-5:00) Canada/Eastern
        <br>(GMT-7:00) Canada/Mountain
        <br>(GMT-3:30) Canada/Newfoundland
        <br>(GMT-8:00) Canada/Pacific
        <br>(GMT-6:00) Canada/Saskatchewan
        <br>(GMT-7:00) Canada/Yukon
        <br>(GMT-4:00) Chile/Continental
        <br>(GMT-6:00) Chile/EasterIsland
        <br>(GMT-5:00) Cuba
        <br>(GMT+2:00) EET
        <br>(GMT-5:00) EST5EDT
        <br>(GMT+2:00) Egypt
        <br>(GMT0:00) Eire
        <br>(GMT0:00) Etc/GMT
        <br>(GMT0:00) Etc/GMT+0
        <br>(GMT-1:00) Etc/GMT+1
        <br>(GMT-10:00) Etc/GMT+10
        <br>(GMT-11:00) Etc/GMT+11
        <br>(GMT-12:00) Etc/GMT+12
        <br>(GMT-2:00) Etc/GMT+2
        <br>(GMT-3:00) Etc/GMT+3
        <br>(GMT-4:00) Etc/GMT+4
        <br>(GMT-5:00) Etc/GMT+5
        <br>(GMT-6:00) Etc/GMT+6
        <br>(GMT-7:00) Etc/GMT+7
        <br>(GMT-8:00) Etc/GMT+8
        <br>(GMT-9:00) Etc/GMT+9
        <br>(GMT0:00) Etc/GMT-0
        <br>(GMT+1:00) Etc/GMT-1
        <br>(GMT+10:00) Etc/GMT-10
        <br>(GMT+11:00) Etc/GMT-11
        <br>(GMT+12:00) Etc/GMT-12
        <br>(GMT+13:00) Etc/GMT-13
        <br>(GMT+14:00) Etc/GMT-14
        <br>(GMT+2:00) Etc/GMT-2
        <br>(GMT+3:00) Etc/GMT-3
        <br>(GMT+4:00) Etc/GMT-4
        <br>(GMT+5:00) Etc/GMT-5
        <br>(GMT+6:00) Etc/GMT-6
        <br>(GMT+7:00) Etc/GMT-7
        <br>(GMT+8:00) Etc/GMT-8
        <br>(GMT+9:00) Etc/GMT-9
        <br>(GMT0:00) Etc/GMT0
        <br>(GMT0:00) Etc/Greenwich
        <br>(GMT0:00) Etc/UCT
        <br>(GMT0:00) Etc/UTC
        <br>(GMT0:00) Etc/Universal
        <br>(GMT0:00) Etc/Zulu
        <br>(GMT+1:00) Europe/Amsterdam
        <br>(GMT+1:00) Europe/Andorra
        <br>(GMT+4:00) Europe/Astrakhan
        <br>(GMT+2:00) Europe/Athens
        <br>(GMT0:00) Europe/Belfast
        <br>(GMT+1:00) Europe/Belgrade
        <br>(GMT+1:00) Europe/Berlin
        <br>(GMT+1:00) Europe/Bratislava
        <br>(GMT+1:00) Europe/Brussels
        <br>(GMT+2:00) Europe/Bucharest
        <br>(GMT+1:00) Europe/Budapest
        <br>(GMT+1:00) Europe/Busingen
        <br>(GMT+2:00) Europe/Chisinau
        <br>(GMT+1:00) Europe/Copenhagen
        <br>(GMT0:00) Europe/Dublin
        <br>(GMT+1:00) Europe/Gibraltar
        <br>(GMT0:00) Europe/Guernsey
        <br>(GMT+2:00) Europe/Helsinki
        <br>(GMT0:00) Europe/Isle_of_Man
        <br>(GMT+3:00) Europe/Istanbul
        <br>(GMT0:00) Europe/Jersey
        <br>(GMT+2:00) Europe/Kaliningrad
        <br>(GMT+2:00) Europe/Kiev
        <br>(GMT+3:00) Europe/Kirov
        <br>(GMT0:00) Europe/Lisbon
        <br>(GMT+1:00) Europe/Ljubljana
        <br>(GMT0:00) Europe/London
        <br>(GMT+1:00) Europe/Luxembourg
        <br>(GMT+1:00) Europe/Madrid
        <br>(GMT+1:00) Europe/Malta
        <br>(GMT+2:00) Europe/Mariehamn
        <br>(GMT+3:00) Europe/Minsk
        <br>(GMT+1:00) Europe/Monaco
        <br>(GMT+3:00) Europe/Moscow
        <br>(GMT+2:00) Europe/Nicosia
        <br>(GMT+1:00) Europe/Oslo
        <br>(GMT+1:00) Europe/Paris
        <br>(GMT+1:00) Europe/Podgorica
        <br>(GMT+1:00) Europe/Prague
        <br>(GMT+2:00) Europe/Riga
        <br>(GMT+1:00) Europe/Rome
        <br>(GMT+4:00) Europe/Samara
        <br>(GMT+1:00) Europe/San_Marino
        <br>(GMT+1:00) Europe/Sarajevo
        <br>(GMT+4:00) Europe/Saratov
        <br>(GMT+3:00) Europe/Simferopol
        <br>(GMT+1:00) Europe/Skopje
        <br>(GMT+2:00) Europe/Sofia
        <br>(GMT+1:00) Europe/Stockholm
        <br>(GMT+2:00) Europe/Tallinn
        <br>(GMT+1:00) Europe/Tirane
        <br>(GMT+2:00) Europe/Tiraspol
        <br>(GMT+4:00) Europe/Ulyanovsk
        <br>(GMT+2:00) Europe/Uzhgorod
        <br>(GMT+1:00) Europe/Vaduz
        <br>(GMT+1:00) Europe/Vatican
        <br>(GMT+1:00) Europe/Vienna
        <br>(GMT+2:00) Europe/Vilnius
        <br>(GMT+3:00) Europe/Volgograd
        <br>(GMT+1:00) Europe/Warsaw
        <br>(GMT+1:00) Europe/Zagreb
        <br>(GMT+2:00) Europe/Zaporozhye
        <br>(GMT+1:00) Europe/Zurich
        <br>(GMT0:00) GB
        <br>(GMT0:00) GB-Eire
        <br>(GMT0:00) GMT
        <br>(GMT0:00) GMT0
        <br>(GMT0:00) Greenwich
        <br>(GMT+8:00) Hongkong
        <br>(GMT0:00) Iceland
        <br>(GMT+3:00) Indian/Antananarivo
        <br>(GMT+6:00) Indian/Chagos
        <br>(GMT+7:00) Indian/Christmas
        <br>(GMT+6:30) Indian/Cocos
        <br>(GMT+3:00) Indian/Comoro
        <br>(GMT+5:00) Indian/Kerguelen
        <br>(GMT+4:00) Indian/Mahe
        <br>(GMT+5:00) Indian/Maldives
        <br>(GMT+4:00) Indian/Mauritius
        <br>(GMT+3:00) Indian/Mayotte
        <br>(GMT+4:00) Indian/Reunion
        <br>(GMT+3:30) Iran
        <br>(GMT+2:00) Israel
        <br>(GMT-5:00) Jamaica
        <br>(GMT+9:00) Japan
        <br>(GMT+12:00) Kwajalein
        <br>(GMT+2:00) Libya
        <br>(GMT+1:00) MET
        <br>(GMT-7:00) MST7MDT
        <br>(GMT-8:00) Mexico/BajaNorte
        <br>(GMT-7:00) Mexico/BajaSur
        <br>(GMT-6:00) Mexico/General
        <br>(GMT+12:00) NZ
        <br>(GMT+12:45) NZ-CHAT
        <br>(GMT-7:00) Navajo
        <br>(GMT+8:00) PRC
        <br>(GMT-8:00) PST8PDT
        <br>(GMT+13:00) Pacific/Apia
        <br>(GMT+12:00) Pacific/Auckland
        <br>(GMT+11:00) Pacific/Bougainville
        <br>(GMT+12:45) Pacific/Chatham
        <br>(GMT+10:00) Pacific/Chuuk
        <br>(GMT-6:00) Pacific/Easter
        <br>(GMT+11:00) Pacific/Efate
        <br>(GMT+13:00) Pacific/Enderbury
        <br>(GMT+13:00) Pacific/Fakaofo
        <br>(GMT+12:00) Pacific/Fiji
        <br>(GMT+12:00) Pacific/Funafuti
        <br>(GMT-6:00) Pacific/Galapagos
        <br>(GMT-9:00) Pacific/Gambier
        <br>(GMT+11:00) Pacific/Guadalcanal
        <br>(GMT+10:00) Pacific/Guam
        <br>(GMT-10:00) Pacific/Honolulu
        <br>(GMT-10:00) Pacific/Johnston
        <br>(GMT+13:00) Pacific/Kanton
        <br>(GMT+14:00) Pacific/Kiritimati
        <br>(GMT+11:00) Pacific/Kosrae
        <br>(GMT+12:00) Pacific/Kwajalein
        <br>(GMT+12:00) Pacific/Majuro
        <br>(GMT-9:30) Pacific/Marquesas
        <br>(GMT-11:00) Pacific/Midway
        <br>(GMT+12:00) Pacific/Nauru
        <br>(GMT-11:00) Pacific/Niue
        <br>(GMT+11:00) Pacific/Norfolk
        <br>(GMT+11:00) Pacific/Noumea
        <br>(GMT-11:00) Pacific/Pago_Pago
        <br>(GMT+9:00) Pacific/Palau
        <br>(GMT-8:00) Pacific/Pitcairn
        <br>(GMT+11:00) Pacific/Pohnpei
        <br>(GMT+11:00) Pacific/Ponape
        <br>(GMT+10:00) Pacific/Port_Moresby
        <br>(GMT-10:00) Pacific/Rarotonga
        <br>(GMT+10:00) Pacific/Saipan
        <br>(GMT-11:00) Pacific/Samoa
        <br>(GMT-10:00) Pacific/Tahiti
        <br>(GMT+12:00) Pacific/Tarawa
        <br>(GMT+13:00) Pacific/Tongatapu
        <br>(GMT+10:00) Pacific/Truk
        <br>(GMT+12:00) Pacific/Wake
        <br>(GMT+12:00) Pacific/Wallis
        <br>(GMT+10:00) Pacific/Yap
        <br>(GMT+1:00) Poland
        <br>(GMT0:00) Portugal
        <br>(GMT+9:00) ROK
        <br>(GMT+8:00) Singapore
        <br>(GMT-4:00) SystemV/AST4
        <br>(GMT-4:00) SystemV/AST4ADT
        <br>(GMT-6:00) SystemV/CST6
        <br>(GMT-6:00) SystemV/CST6CDT
        <br>(GMT-5:00) SystemV/EST5
        <br>(GMT-5:00) SystemV/EST5EDT
        <br>(GMT-10:00) SystemV/HST10
        <br>(GMT-7:00) SystemV/MST7
        <br>(GMT-7:00) SystemV/MST7MDT
        <br>(GMT-8:00) SystemV/PST8
        <br>(GMT-8:00) SystemV/PST8PDT
        <br>(GMT-9:00) SystemV/YST9
        <br>(GMT-9:00) SystemV/YST9YDT
        <br>(GMT+3:00) Turkey
        <br>(GMT0:00) UCT
        <br>(GMT-9:00) US/Alaska
        <br>(GMT-10:00) US/Aleutian
        <br>(GMT-7:00) US/Arizona
        <br>(GMT-6:00) US/Central
        <br>(GMT-5:00) US/East-Indiana
        <br>(GMT-5:00) US/Eastern
        <br>(GMT-10:00) US/Hawaii
        <br>(GMT-6:00) US/Indiana-Starke
        <br>(GMT-5:00) US/Michigan
        <br>(GMT-7:00) US/Mountain
        <br>(GMT-8:00) US/Pacific
        <br>(GMT-11:00) US/Samoa
        <br>(GMT0:00) UTC
        <br>(GMT0:00) Universal
        <br>(GMT+3:00) W-SU
        <br>(GMT0:00) WET
        <br>(GMT0:00) Zulu
        <br>(GMT-5:00) EST
        <br>(GMT-10:00) HST
        <br>(GMT-7:00) MST
        <br>(GMT+9:30) ACT
        <br>(GMT+10:00) AET
        <br>(GMT-3:00) AGT
        <br>(GMT+2:00) ART
        <br>(GMT-9:00) AST
        <br>(GMT-3:00) BET
        <br>(GMT+6:00) BST
        <br>(GMT+2:00) CAT
        <br>(GMT-3:30) CNT
        <br>(GMT-6:00) CST
        <br>(GMT+8:00) CTT
        <br>(GMT+3:00) EAT
        <br>(GMT+1:00) ECT
        <br>(GMT-5:00) IET
        <br>(GMT+5:30) IST
        <br>(GMT+9:00) JST
        <br>(GMT+13:00) MIT
        <br>(GMT+4:00) NET
        <br>(GMT+12:00) NST
        <br>(GMT+5:00) PLT
        <br>(GMT-7:00) PNT
        <br>(GMT-4:00) PRT
        <br>(GMT-8:00) PST
        <br>(GMT+11:00) SST
        <br>(GMT+7:00) VST
        
	</div>

</body>
</html>